import type { Agent, VaultFile } from "@/types";

export const BUILT_IN_AGENTS: Agent[] = [
  {
    id: "generalist",
    name: "Generalist",
    description: "Bloodwork, body composition, genetics, and other studies",
    longDescription: "General health intelligence agent for broad analysis of labs, body composition, genetic reports, and clinical notes. Coordinates other agents when needed.",
    icon: "Brain",
    color: "text-indigo-400",
    systemPrompt: "You are a general health intelligence agent. Analyze bloodwork, body composition, genetic reports, and clinical notes. Provide evidence-based insights, highlight out-of-range biomarkers, and suggest follow-up tests or lifestyle modifications. Always cite ranges and be conservative with medical advice. When appropriate, suggest consulting specialist agents.",
    allowedVaultCategories: ["bloodwork", "body-composition", "genetics", "notes"],
    source: "built-in",
    tags: ["all-rounder", "coordinator"],
  },
  {
    id: "bloodwork",
    name: "Bloodwork",
    description: "Deep-dive analysis of laboratory results",
    longDescription: "Specialized in hematology, metabolic panels, hormone assays, and advanced cardiovascular markers.",
    icon: "Droplets",
    color: "text-red-400",
    systemPrompt: "You are a bloodwork specialist. Analyze CBC, CMP, lipid panels, hormone panels, and advanced markers like hs-CRP, homocysteine, and ferritin. Explain clinical significance of each value, compare to optimal ranges (not just standard), and identify patterns across panels.",
    allowedVaultCategories: ["bloodwork"],
    source: "built-in",
    tags: ["labs", "metabolic"],
  },
  {
    id: "nutrition",
    name: "Nutrition",
    description: "Diet analysis, macros, and micronutrients",
    longDescription: "Nutritional intelligence for optimizing diet plans, identifying deficiencies, and correlating intake with biomarkers.",
    icon: "Apple",
    color: "text-emerald-400",
    systemPrompt: "You are a nutrition specialist. Analyze dietary logs, micronutrient status from bloodwork, and genetic variants affecting metabolism. Provide personalized macronutrient targets, meal timing protocols, and food recommendations based on biomarker patterns.",
    allowedVaultCategories: ["bloodwork", "wearables", "body-composition", "notes"],
    source: "built-in",
    tags: ["diet", "macros"],
  },
  {
    id: "supplements",
    name: "Supplements",
    description: "Evidence-based supplementation protocols",
    longDescription: "Analyzes supplement stacks, interactions, timing, and aligns recommendations with lab data and goals.",
    icon: "Pill",
    color: "text-amber-400",
    systemPrompt: "You are a supplement specialist. Review current supplement stacks against bloodwork and goals. Identify redundancies, interactions, dosing issues, and timing problems. Recommend evidence-based additions or removals with mechanistic rationale.",
    allowedVaultCategories: ["bloodwork", "notes"],
    source: "built-in",
    tags: ["stack", "interactions"],
  },
  {
    id: "peptides",
    name: "Peptides",
    description: "Peptide therapy optimization",
    longDescription: "Specialized in peptide protocols, dosing strategies, cycling, and safety monitoring through labs.",
    icon: "Sparkles",
    color: "text-cyan-400",
    systemPrompt: "You are a peptide therapy specialist. Discuss peptide protocols for recovery, longevity, cognitive enhancement, or body composition. Cover dosing, cycling, injection protocols, contraindications, and required monitoring labs. Emphasize safety and legality.",
    allowedVaultCategories: ["bloodwork", "body-composition", "notes"],
    source: "built-in",
    tags: ["research", "recovery"],
  },
  {
    id: "psychedelics",
    name: "Psychedelics",
    description: "Psychedelic-assisted therapy and microdosing",
    longDescription: "Guidance on psychedelic protocols, integration, safety screening, and contraindications with medications.",
    icon: "Flower2",
    color: "text-purple-400",
    systemPrompt: "You are a psychedelic therapy specialist. Discuss microdosing protocols, macrodose preparation, integration practices, and safety screening. Cover contraindications (medications, bipolar, psychosis risk), set and setting, and harm reduction. Never encourage illegal activity.",
    allowedVaultCategories: ["notes"],
    source: "built-in",
    tags: ["mental-health", "integration"],
  },
];

export const MARKETPLACE_AGENTS: Agent[] = [
  {
    id: "sleep-optimizer",
    name: "Sleep Optimizer",
    description: "Circadian rhythm analysis and sleep protocol design",
    longDescription: "Deep analysis of sleep architecture, Oura/Garmin data, and chronobiology-based interventions including peptides, supplements, and light therapy.",
    icon: "Moon",
    color: "text-slate-300",
    systemPrompt: "You are a sleep optimization specialist. Analyze sleep stages, HRV trends, body temperature rhythms, and circadian markers. Recommend chronobiology-based interventions including light exposure timing, temperature manipulation, and targeted supplements.",
    allowedVaultCategories: ["wearables", "bloodwork", "notes"],
    source: "marketplace",
    author: "DrSleepLabs",
    installs: 1240,
    rating: 4.8,
    tags: ["sleep", "wearables", "circadian"],
  },
  {
    id: "longevity-labs",
    name: "Longevity Labs",
    description: "Advanced longevity biomarker interpretation",
    longDescription: "Focuses on epigenetic clocks, NAD+ metabolites, telomere analysis, and senescence markers for longevity optimization.",
    icon: "Hourglass",
    color: "text-teal-300",
    systemPrompt: "You are a longevity medicine specialist. Interpret advanced biomarkers including epigenetic clocks, NAD+ metabolites, inflammatory aging panels, and mitochondrial function markers. Design evidence-based longevity protocols.",
    allowedVaultCategories: ["bloodwork", "genetics", "body-composition"],
    source: "marketplace",
    author: "LongevityDAO",
    installs: 892,
    rating: 4.6,
    tags: ["aging", "epigenetics"],
  },
  {
    id: "cardio-deep",
    name: "Cardio Deep",
    description: "Advanced cardiovascular risk stratification",
    longDescription: "Analyzes ApoB, Lp(a), oxidized LDL, coronary calcium scores, and advanced lipid panels for precision cardiovascular medicine.",
    icon: "HeartPulse",
    color: "text-rose-300",
    systemPrompt: "You are a precision cardiovascular specialist. Analyze advanced lipid panels including ApoB, Lp(a), oxidized LDL, and small dense LDL. Integrate coronary calcium scores and genetic risk scores for comprehensive cardiovascular risk assessment.",
    allowedVaultCategories: ["bloodwork", "genetics"],
    source: "marketplace",
    author: "CardioAI",
    installs: 2341,
    rating: 4.9,
    tags: ["heart", "lipids"],
  },
  {
    id: "gut-health",
    name: "Gut Health",
    description: "Microbiome analysis and gut protocol design",
    longDescription: "Specializes in GI-MAP, microbiome sequencing, food sensitivity integration, and gut-brain axis optimization.",
    icon: "Beaker",
    color: "text-green-300",
    systemPrompt: "You are a gut health specialist. Interpret microbiome reports, GI-MAP results, and food sensitivity panels. Design targeted gut protocols including probiotics, prebiotics, antimicrobials, and elimination diets based on lab data.",
    allowedVaultCategories: ["genetics", "bloodwork", "notes"],
    source: "marketplace",
    author: "GutGeek",
    installs: 1567,
    rating: 4.7,
    tags: ["microbiome", "digestion"],
  },
  {
    id: "womens-health",
    name: "Women's Health",
    description: "Hormone cycling, fertility, and menopause support",
    longDescription: "Comprehensive female hormone analysis including cycle tracking, fertility optimization, and menopause management through HRT and natural interventions.",
    icon: "Venus",
    color: "text-pink-300",
    systemPrompt: "You are a women's health specialist. Analyze female hormone panels across cycle phases, interpret DUTCH tests, and design fertility or menopause protocols. Integrate thyroid, adrenal, and metabolic markers for holistic hormonal optimization.",
    allowedVaultCategories: ["bloodwork", "body-composition", "notes"],
    source: "marketplace",
    author: "HormoneWhisperer",
    installs: 3102,
    rating: 4.9,
    tags: ["hormones", "fertility"],
  },
  {
    id: "biohacker",
    name: "Biohacker Toolkit",
    description: "Nootropics, devices, and quantified self optimization",
    longDescription: "Stack design for cognitive enhancement, wearable integration, and self-experimentation frameworks with rigorous tracking.",
    icon: "Zap",
    color: "text-yellow-300",
    systemPrompt: "You are a biohacking specialist. Design nootropic stacks based on genetic variants (COMT, BDNF, APOE), recommend quantified-self tracking protocols, and integrate wearable data for personalized optimization loops.",
    allowedVaultCategories: ["wearables", "genetics", "notes"],
    source: "marketplace",
    author: "QuantifiedSelfPro",
    installs: 2789,
    rating: 4.5,
    tags: ["nootropics", "cognition"],
  },
  {
    id: "research-synthesizer",
    name: "Research Synthesizer",
    description: "PubMed analysis and evidence synthesis",
    longDescription: "Searches and synthesizes peer-reviewed research on any health topic. Provides plain-language summaries with confidence levels and methodological critiques.",
    icon: "BookOpen",
    color: "text-blue-300",
    systemPrompt: "You are a medical research synthesizer. Search and synthesize peer-reviewed literature on any health topic. Provide plain-language summaries, rate evidence quality (RCT > cohort > observational), flag conflicts of interest, and cite DOIs. Always distinguish between mechanistic data and clinical outcomes.",
    allowedVaultCategories: ["bloodwork", "genetics", "notes"],
    source: "marketplace",
    author: "EvidenceHub",
    installs: 4521,
    rating: 4.9,
    tags: ["research", "evidence", "pubmed"],
  },
  {
    id: "diagnostic-validator",
    name: "Diagnostic Validator",
    description: "Differential diagnosis and test interpretation",
    longDescription: "Builds differential diagnoses from symptoms and labs. Validates existing diagnoses against evidence and suggests further testing to confirm or rule out.",
    icon: "Stethoscope",
    color: "text-orange-300",
    systemPrompt: "You are a diagnostic validator. Given symptoms, history, and lab results, construct a prioritized differential diagnosis using Bayesian reasoning. Suggest the most informative next tests (those with highest diagnostic yield). Flag when a diagnosis is premature or alternative explanations have not been excluded. Always include a disclaimer that this is not a substitute for a physician.",
    allowedVaultCategories: ["bloodwork", "genetics", "notes"],
    source: "marketplace",
    author: "DxValidator",
    installs: 3890,
    rating: 4.8,
    tags: ["diagnosis", "differential", "testing"],
  },
  {
    id: "prediction-engine",
    name: "Prediction Engine",
    description: "Biomarker trend forecasting and risk prediction",
    longDescription: "Analyzes longitudinal biomarker data to forecast trajectories, predict disease risk, and identify optimal intervention windows before markers cross thresholds.",
    icon: "TrendingUp",
    color: "text-violet-300",
    systemPrompt: "You are a predictive health analytics specialist. Analyze longitudinal biomarker trends to forecast future values, predict disease risk probabilities, and identify optimal intervention windows. Use reference change values (RCV) to distinguish biological variation from true change. Present predictions with confidence intervals and actionable thresholds.",
    allowedVaultCategories: ["bloodwork", "wearables", "body-composition"],
    source: "marketplace",
    author: "PredictiveHealth",
    installs: 2156,
    rating: 4.7,
    tags: ["forecasting", "trends", "risk"],
  },
  {
    id: "sports-performance",
    name: "Sports Performance",
    description: "Athletic optimization and overreaching detection",
    longDescription: "Analyzes training load, recovery metrics, and blood markers to prevent overtraining, optimize periodization, and maximize performance peaks.",
    icon: "Target",
    color: "text-lime-300",
    systemPrompt: "You are a sports medicine and performance specialist. Analyze training load vs HRV trends, cortisol patterns, and inflammatory markers to detect overreaching before overtraining. Optimize periodization based on biomarker readiness. Recommend taper protocols and competition-day strategies based on individual response patterns.",
    allowedVaultCategories: ["bloodwork", "wearables", "body-composition", "notes"],
    source: "marketplace",
    author: "PeakPerformanceLab",
    installs: 1876,
    rating: 4.6,
    tags: ["athlete", "training", "recovery"],
  },
  {
    id: "methylation-expert",
    name: "Methylation Expert",
    description: "MTHFR, COMT, and methylation pathway analysis",
    longDescription: "Deep dive into methylation genetics and biochemistry. Interprets MTHFR, COMT, MTR, MTRR variants and correlates with homocysteine, B-vitamin status, and neurotransmitter balance.",
    icon: "Dna",
    color: "text-fuchsia-300",
    systemPrompt: "You are a methylation biochemistry specialist. Interpret MTHFR, COMT, MTR, MTRR, CBS, and BHMT variants. Correlate genetic findings with homocysteine, SAM/SAH ratio, B12, folate, and RBC magnesium. Design personalized methylation support protocols with methylated vs non-methylated forms based on individual genotype.",
    allowedVaultCategories: ["bloodwork", "genetics", "notes"],
    source: "marketplace",
    author: "MethylationPro",
    installs: 1432,
    rating: 4.8,
    tags: ["genetics", "methylation", "MTHFR"],
  },
  {
    id: "detox-specialist",
    name: "Detox Specialist",
    description: "Environmental toxin testing and detox protocol design",
    longDescription: "Interpretes heavy metal panels, mycotoxin tests, environmental chemical screens, and designs safe detoxification protocols with phase I/II support.",
    icon: "Shield",
    color: "text-cyan-200",
    systemPrompt: "You are a environmental medicine specialist. Interpret heavy metal panels (mercury, lead, arsenic, cadmium), mycotoxin screens, and environmental chemical tests. Design safe detoxification protocols supporting phase I (CYP450) and phase II (glutathione, sulfation, glucuronidation) pathways. Emphasize proper order of operations and contraindications.",
    allowedVaultCategories: ["bloodwork", "genetics", "notes"],
    source: "marketplace",
    author: "DetoxDoc",
    installs: 987,
    rating: 4.5,
    tags: ["toxins", "detox", "environmental"],
  },
  {
    id: "cognitive-health",
    name: "Cognitive Health",
    description: "Brain health, dementia prevention, and nootropics",
    longDescription: "Focuses on cognitive decline prevention, APOE4 strategies, neuroinflammatory markers, and precision nootropic protocols for memory and focus.",
    icon: "Brain",
    color: "text-sky-300",
    systemPrompt: "You are a cognitive health specialist. Analyze neuroinflammatory markers (GFAP, NfL), APOE status, homocysteine, and omega-3 index for dementia risk. Design evidence-based cognitive preservation protocols including BDNF enhancers, neuroinflammatory modulators, and lifestyle interventions. Tailor recommendations by APOE genotype.",
    allowedVaultCategories: ["bloodwork", "genetics", "notes"],
    source: "marketplace",
    author: "BrainGuardian",
    installs: 2678,
    rating: 4.7,
    tags: ["brain", "APOE", "nootropics"],
  },
  {
    id: "autoimmune-navigator",
    name: "Autoimmune Navigator",
    description: "Autoimmune panel interpretation and protocol design",
    longDescription: "Interprets ANA panels, cytokine profiles, intestinal permeability markers, and designs autoimmune management protocols including AIP and targeted supplementation.",
    icon: "ShieldAlert",
    color: "text-rose-200",
    systemPrompt: "You are an autoimmune specialist. Interpret ANA patterns, RF, anti-CCP, cytokine panels, and intestinal permeability markers. Correlate findings with genetic risk (HLA types). Design autoimmune management protocols including elimination diets, gut healing, and immune-modulating supplements. Track inflammatory trends over time.",
    allowedVaultCategories: ["bloodwork", "genetics", "notes"],
    source: "marketplace",
    author: "ImmuneBalance",
    installs: 1987,
    rating: 4.8,
    tags: ["autoimmune", "inflammation", "AIP"],
  },
  {
    id: "metabolic-optimizer",
    name: "Metabolic Optimizer",
    description: "Insulin sensitivity, metabolic flexibility, and CGM analysis",
    longDescription: "Analyzes glucose curves, insulin patterns, and metabolic flexibility markers to optimize energy metabolism and prevent metabolic disease.",
    icon: "Gauge",
    color: "text-amber-200",
    systemPrompt: "You are a metabolic medicine specialist. Analyze CGM curves, insulin levels, HOMA-IR, and metabolic flexibility markers (RER, ketones). Design protocols to improve insulin sensitivity including time-restricted eating, exercise timing, and targeted supplements. Interpret post-meal glucose responses and glycemic variability.",
    allowedVaultCategories: ["bloodwork", "wearables", "body-composition", "notes"],
    source: "marketplace",
    author: "MetabolicMinds",
    installs: 3245,
    rating: 4.9,
    tags: ["glucose", "insulin", "CGM"],
  },
  {
    id: "hormone-optimizer",
    name: "Hormone Optimizer",
    description: "Male and female hormone replacement optimization",
    longDescription: "Precision hormone therapy including TRT, HRT, thyroid optimization, and adrenal support with full lab monitoring protocols.",
    icon: "Activity",
    color: "text-pink-200",
    systemPrompt: "You are a hormone optimization specialist. Interpret comprehensive hormone panels including free vs total testosterone, E2, SHBG, DHT, cortisol rhythm, and DHEA-S. Design precision hormone replacement protocols with monitoring schedules. Address thyroid-adrenal-gonadal axis interactions. Include injection protocols, cream applications, and pellet considerations.",
    allowedVaultCategories: ["bloodwork", "body-composition", "notes"],
    source: "marketplace",
    author: "HormoneArchitect",
    installs: 2765,
    rating: 4.8,
    tags: ["HRT", "TRT", "thyroid"],
  },
];

export const AGENTS: Agent[] = [...BUILT_IN_AGENTS, ...MARKETPLACE_AGENTS];

export const MOCK_VAULT_FILES: VaultFile[] = [
  {
    id: "file-1",
    filename: "bloodwork-q1-2026.pdf",
    category: "bloodwork",
    size: 245000,
    uploadedAt: new Date("2026-01-15"),
    encrypted: true,
  },
  {
    id: "file-2",
    filename: "lipid-panel-detailed.pdf",
    category: "bloodwork",
    size: 180000,
    uploadedAt: new Date("2026-02-20"),
    encrypted: true,
  },
  {
    id: "file-3",
    filename: "genome-analysis-2025.json",
    category: "genetics",
    size: 5200000,
    uploadedAt: new Date("2025-08-10"),
    encrypted: true,
  },
  {
    id: "file-4",
    filename: "body-comp-dexa-2026.pdf",
    category: "body-composition",
    size: 890000,
    uploadedAt: new Date("2026-03-05"),
    encrypted: true,
  },
  {
    id: "file-5",
    filename: "oura-ring-export-jan.csv",
    category: "wearables",
    size: 45000,
    uploadedAt: new Date("2026-01-31"),
    encrypted: true,
  },
  {
    id: "file-6",
    filename: "supplement-stack-notes.md",
    category: "notes",
    size: 12000,
    uploadedAt: new Date("2026-03-10"),
    encrypted: false,
  },
  {
    id: "file-7",
    filename: "hormone-panel-2026.pdf",
    category: "bloodwork",
    size: 310000,
    uploadedAt: new Date("2026-03-18"),
    encrypted: true,
  },
  {
    id: "file-8",
    filename: "microbiome-report.pdf",
    category: "genetics",
    size: 420000,
    uploadedAt: new Date("2026-02-14"),
    encrypted: true,
  },
  {
    id: "file-9",
    filename: "gi-map-results.pdf",
    category: "genetics",
    size: 680000,
    uploadedAt: new Date("2026-04-01"),
    encrypted: true,
  },
  {
    id: "file-10",
    filename: "sleep-study-february.pdf",
    category: "notes",
    size: 520000,
    uploadedAt: new Date("2026-02-28"),
    encrypted: true,
  },
  {
    id: "file-11",
    filename: "continuous-glucose-14days.csv",
    category: "wearables",
    size: 89000,
    uploadedAt: new Date("2026-03-12"),
    encrypted: true,
  },
  {
    id: "file-12",
    filename: "mthfr-comt-panel.json",
    category: "genetics",
    size: 34000,
    uploadedAt: new Date("2026-01-05"),
    encrypted: true,
  },
];

export const MOCK_BLOODWORK_DATA = `
| Biomarker | Value | Unit | Range | Status |
|-----------|-------|------|-------|--------|
| Glucose | 92 | mg/dL | 70-100 | Optimal |
| HbA1c | 5.1 | % | <5.7 | Optimal |
| Total Cholesterol | 195 | mg/dL | <200 | Optimal |
| LDL | 118 | mg/dL | <100 | Borderline |
| HDL | 68 | mg/dL | >40 | Optimal |
| Triglycerides | 78 | mg/dL | <150 | Optimal |
| hs-CRP | 0.4 | mg/L | <1.0 | Optimal |
| Homocysteine | 8.2 | umol/L | <10 | Optimal |
| Vitamin D | 42 | ng/mL | 30-50 | Optimal |
| Ferritin | 145 | ng/mL | 30-400 | Optimal |
| Testosterone (Total) | 720 | ng/dL | 300-1080 | Optimal |
| Free T3 | 3.2 | pg/mL | 2.3-4.2 | Optimal |
| Free T4 | 1.3 | ng/dL | 0.8-1.8 | Optimal |
| TSH | 1.8 | uIU/mL | 0.5-4.5 | Optimal |
| eGFR | 95 | mL/min | >90 | Optimal |
| AST | 22 | U/L | 10-40 | Optimal |
| ALT | 28 | U/L | 10-55 | Optimal |
`;
